name: ðŸ–¥ Deploy to server
on:
  push:
    branches: [ publish ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ðŸ”‘ Set up SSH Cardentials
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy.key
          sudo chmod 600 ~/.ssh/deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      # (optional - only needed if your config uses environment variables)
      - name: ðŸ“ Create env file
        run: |
          touch .env
          echo DEPLOY_USER=${{ secrets.DEPLOY_USER }} >> .env
          echo DEPLOY_HOST=${{ secrets.DEPLOY_HOST }} >> .env
          echo DEPLOY_PORT=${{ secrets.DEPLOY_PORT }} >> .env

      - name: ðŸ“¦ Install PM2
        run: npm i pm2

      - name: ðŸ”¥ Deploy
        run: pm2 deploy ecosystem.config.js production
